name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: Tests vault-java-driver     # Name of the check run which will be created
          path: '**/*.xml'                  # Path to test results (inside artifact .zip)
          reporter: java-junit
          list-suites: 'all'
          list-tests: 'all'

